### ISSUE TITLE
Error when calling HTTPClientDoRequest

### ISSUE THREAD

**Issue by dsteplight** [gabesoft/vim-ags#8]
Every time I make a request I get an error. I had to install Python's request library, but this error exists after the install.

**HTTP_Client_Response**" [New File]
Error detected while processing function <SNR>65_DoHTTPRequest:
line   11:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/dsteplight/.vim/bundle/vim-http-client/plugin/http_client.py", line 124, in do_request_from_buffer
    open_scratch_buffer(response, vim_ft)
  File "/Users/dsteplight/.vim/bundle/vim-http-client/plugin/http_client.py", line 113, in open_scratch_buffer
    vim.current.buffer[:] = contents
TypeError: bad argument type for built-in operation

**Comment by gabesoft** [comment]
I think that's from a different plugin. See https://github.com/aquach/vim-http-client

**Comment by dsteplight** [comment]
Yes, you are correct. Pasted in the wrong window.
